### ISSUE TITLE
Using framework on OpenShift 4

### ISSUE THREAD

**Issue by blublinsky** [jvm-operators/abstract-operator#45]
### Describe the problem:

  * On OpenShift 4, the framework does not recognize OpenShift:
2019-04-18 19:33:39 INFO  Entrypoint:217 - https://172.30.0.1/oapi returned 404. We are not on OpenShift. Assuming, we are on Kubernetes. As a result, Kubernetes not OS client is used and everything fails

#### Steps to reproduce:

  1. Try to run operator on OpenShift 4
  
#### Observed Results:

 VM settings:
    Max. Heap Size (Estimated): 3.76G
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM

2019-04-18 19:33:38 INFO  Entrypoint:56 - Starting..
2019-04-18 19:33:39 INFO  Entrypoint:217 - https://172.30.0.1/oapi returned 404. We are not on OpenShift. Assuming, we are on Kubernetes.
2019-04-18 19:33:39 INFO  Manifests:193 - 55 attributes loaded from 52 stream(s) in 51ms, 55 saved, 724 ignored: ["Ant-Version", "Archiver-Version", "Automatic-Module-Name", "Bnd-LastModified", "Build-Jdk", "Build-Timestamp", "Built-By", "Bundle-ClassPath", "Bundle-ContactAddress", "Bundle-Description", "Bundle-DocURL", "Bundle-License", "Bundle-ManifestVersion", "Bundle-Name", "Bundle-RequiredExecutionEnvironment", "Bundle-SymbolicName", "Bundle-Vendor", "Bundle-Version", "Created-By", "DynamicImport-Package", "Export-Package", "Extension-Name", "Fragment-Host", "Ignore-Package", "Implementation-Build", "Implementation-Build-Date", "Implementation-Title", "Implementation-URL", "Implementation-Vendor", "Implementation-Vendor-Id", "Implementation-Version", "Import-Package", "Include-Resource", "JCabi-Build", "JCabi-Date", "JCabi-Version", "Java-Vendor", "Java-Version", "Main-Class", "Manifest-Version", "Os-Arch", "Os-Name", "Os-Version", "Package", "Private-Package", "Require-Capability", "Scm-Connection", "Scm-Revision", "Scm-Url", "Specification-Title", "Specification-Vendor", "Specification-Version", "Tool", "X-Compile-Source-JDK", "X-Compile-Target-JDK"]
2019-04-18 19:33:39 INFO  Entrypoint:236 - 
[31mOperator[0m has started in version [32m0.6.1[0m.

2019-04-18 19:33:39 INFO  Entrypoint:239 - Git sha: [33mtags/LANG_3_2_1_RC1@r1555582; 2014-01-05 18:01:10+0100[0m
2019-04-18 19:33:39 INFO  Entrypoint:241 - ==================

2019-04-18 19:33:39 INFO  Entrypoint:76 - [33mKubernetes[0m environment detected.
2019-04-18 19:33:43 INFO  AbstractOperator:246 - Starting 'FlinkCluster' operator for namespace flink1
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:238)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:191)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:384)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:165)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:607)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:67)
	at io.radanalytics.operator.common.crd.CrdDeployer.initCrds(CrdDeployer.java:34)
	at io.radanalytics.operator.common.AbstractOperator.start(AbstractOperator.java:249)
	at io.radanalytics.operator.Entrypoint.lambda$runForNamespace$6(Entrypoint.java:153)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at io.radanalytics.operator.Entrypoint.runForNamespace(Entrypoint.java:136)
	at io.radanalytics.operator.Entrypoint.run(Entrypoint.java:92)
	at io.radanalytics.operator.Entrypoint.main(Entrypoint.java:60)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "nullable" (class io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps), not marked as ignorable (36 known properties: "definitions", "default", "$schema", "multipleOf", "minItems", "exclusiveMinimum", "not", "allOf", "additionalItems", "id", "oneOf", "required", "maximum", "exclusiveMaximum", "anyOf", "minProperties", "externalDocs", "dependencies", "example", "$ref", "properties", "format", "additionalProperties", "description", "enum", "minimum", "pattern", "minLength", "patternProperties", "maxLength", "uniqueItems", "maxProperties", "type", "maxItems", "items", "title"])
 at [Source: (BufferedInputStream); line: 1, column: 202859] (through reference chain: io.fabric8.kubernetes.api.model.apiextensions.CustomResourceDefinitionList["items"]->java.util.ArrayList[31]->io.fabric8.kubernetes.api.model.apiextensions.CustomResourceDefinition["spec"]->io.fabric8.kubernetes.api.model.apiextensions.CustomResourceDefinitionSpec["validation"]->io.fabric8.kubernetes.api.model.apiextensions.CustomResourceValidation["openAPIV3Schema"]->io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps["properties"]->java.util.LinkedHashMap["spec"]->io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps["properties"]->java.util.LinkedHashMap["observedConfig"]->io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps["nullable"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3077)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:236)
	... 15 more

  
#### Expected Results:

  * Normal execution

**Comment by blublinsky** [comment]
It looks like changing a line https://github.com/jvm-operators/abstract-operator/blob/master/src/main/java/io/radanalytics/operator/Entrypoint.java#L200 from
urlBuilder.addPathSegment("oapi");
to
urlBuilder.addPathSegment("apis/route.openshift.io/v1");
does the trick and works in both OS3 and OS4

**Comment by Jiri-Kremser** [comment]
Thanks for spotting this issue. In the exception, it looks like the issue happens when creating the CRDs in the `io.radanalytics.operator.common.crd.CrdDeployer.initCrds(CrdDeployer.java:34)` it's a harmless error if you don't care about the validation, it's just ignored and it tries to create the CRDs without the schema validation. If you do care about the validation of your custom resources by kubernetes, check the recent [changes](https://github.com/radanalyticsio/spark-operator/pull/222) I had to make to spark operator to make it work. In short, the K8s validation is far from perfect and it contains only a sub-set of features as the json schema or the openAPIV3Schema specification. For instance one can't use definitions and refs, dependencies, default values, etc. Something could have been fixed on the abstract-operator level (like removing the default values, when [creating](https://github.com/jvm-operators/abstract-operator/commit/d8cef499524e0b8f2352acec14d831a3f46b2301#diff-52f03e99289fcf30d039920b62bd1301R93) the schema), but not everything was doable in this library, so if you want the schema, you can't use the definitions for instance and have to "dereference" everything, like in that PR to spark op.

wrt. `urlBuilder.addPathSegment("apis/route.openshift.io/v1");`, I will give it a try locally and if it works, I'll put the change in, thanks!

**Comment by Jiri-Kremser** [comment]
fixed in https://github.com/jvm-operators/abstract-operator/commit/95493c706705012f5feab93dea85d648e2697515

**Comment by jkremser** [comment]
reopening the issue, because I also hit this even w/ the change 95493c7 in
